<a href="https://colab.research.google.com/github/roshnik1610/Welcome-to-Open-Source/blob/master/Customer_churn_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df= pd.read_csv('/content/customer_churn (1).csv')

In [ ]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
two_mail_yes= df.copy()

In [ ]:
two_mail_yes= df[(df['Contract']=='Two year') & (df['Churn']=='Yes') & (df['PaymentMethod']=='Mailed check')]

In [ ]:
two_mail_yes

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
268,6323-AYBRX,Male,0,No,No,59,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1099.6,Yes
5947,7951-QKZPL,Female,0,Yes,Yes,33,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,24.50,740.3,Yes
6680,9412-ARGBX,Female,0,No,Yes,48,Yes,No,Fiber optic,No,...,Yes,Yes,Yes,No,Two year,Yes,Mailed check,95.50,4627.85,Yes

In [ ]:
'''Linear Regression:
a.
Build a simple linear model where dependent variable is ‘MonthlyCharges’ and
independent variable is ‘tenure’
i. Divide the dataset into train and test sets in 70:30 ratio.
ii. Build the model on train set and predict the values on test set
iii. After predicting the values, find the root mean square error
iv. Find out the error in prediction & store the result in ‘error’
v.  Find the root mean square error '''

'Linear Regression: \na. \nBuild a simple linear model where dependent variable is ‘MonthlyCharges’ and \nindependent variable is ‘tenure’ \ni. \nii. \niii. \niv. \nv. \nDivide the dataset into train and test sets in 70:30 ratio.  \nBuild the model on train set and predict the values on test set \nAfter predicting the values, find the root mean square error \nFind out the error in prediction & store the result in ‘error’ \nFind the root mean square error '

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df['Contract'].dtype

dtype('O')

In [ ]:
le=LabelEncoder()

In [ ]:
for col in df.columns:
  if(df[col].dtype=='object'):
    df[col]=le.fit_transform(df[col])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   int64
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int64
 7   MultipleLines     7043 non-null   int64
 8   InternetService   7043 non-null   int64
 9   OnlineSecurity    7043 non-null   int64
 10  OnlineBackup      7043 non-null   int64
 11  DeviceProtection  7043 non-null   int64
 12  TechSupport       7043 non-null   int64
 13  StreamingTV       7043 non-null   int64
 14  StreamingMovies   7043 non-null   int64
 15  Contract          7043 non-null   int64
 16  PaperlessBilling  7043 non-null   int64
 17  PaymentMethod     7043 non-null   int64
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   int64
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(20)
memory usage: 1.1 MB

In [ ]:
y=df['MonthlyCharges']

In [ ]:
x=pd.DataFrame(df['tenure'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=0)

In [ ]:
x_train

      tenure
3580       9
2364      14
6813      64
789       72
561        3
...      ...
4931      15
3264      10
1653      58
2607       1
2732       4

[4930 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model= LinearRegression()

In [ ]:


model.fit(x_train,y_train)

LinearRegression()

In [ ]:

y_pred= model.predict(x_test)

In [ ]:
from sklearn.metrics import *

In [ ]:
r2_score(y_pred,y_test)

-15.457198899999064

In [ ]:
mse= mean_squared_error(y_pred,y_test)

In [ ]:
mse

864.0415701364655

In [ ]:
error= y_test- y_pred

In [ ]:
error

2200    -2.750896
4627    43.619033
3225    12.759602
2828   -35.219402
3768     6.236115
          ...
4448    35.521524
1231     3.155688
3304    34.328286
4805   -46.083636
5843    15.954442
Name: MonthlyCharges, Length: 2113, dtype: float64

In [ ]:
rmse= np.sqrt(mse)

In [ ]:
rmse

np.float64(29.394584027273893)

In [ ]:
'''Logistic Regression:
a.
Build a simple logistic regression modelwhere dependent variable is ‘Churn’ &
independent variable is ‘MonthlyCharges’
i. Divide the dataset in 65:35 ratio
ii. Build the model on train set and predict the values on test set
iii. Build the confusion matrix and get the accuracy score
 '''

'Logistic Regression: \na. \nBuild a simple logistic regression modelwhere dependent variable is ‘Churn’ & \nindependent variable is ‘MonthlyCharges’ \ni. Divide the dataset in 65:35 ratio \nii. Build the model on train set and predict the values on test set\niii. Build the confusion matrix and get the accuracy score\nb.  \nBuild a multiple logistic regression model where dependent variable is ‘Churn’ & \nindependent variables are ‘tenure’ & ‘MonthlyCharges’ \ni. Divide the dataset in 80:20 ratio \nii. Build the model on train set and predict the values on test set \niii. Build the confusion matrix and get the accuracy score '

In [ ]:
x=pd.DataFrame(df['MonthlyCharges'])

In [ ]:
y=df['Churn']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=65,random_state=11)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model= LogisticRegression()

In [ ]:


model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred= model.predict(x_test)

In [ ]:
from sklearn.metrics import *

In [ ]:
accuracy_score(y_pred,y_test)

0.735024362281456

In [ ]:
confusion_matrix(y_pred,y_test)

array([[5129, 1849],
       [   0,    0]])

In [ ]:
'''b.
Build a multiple logistic regression model where dependent variable is ‘Churn’ &
independent variables are ‘tenure’ & ‘MonthlyCharges’
i. Divide the dataset in 80:20 ratio
ii. Build the model on train set and predict the values on test set
iii. Build the confusion matrix and get the accuracy score'''

'b.  \nBuild a multiple logistic regression model where dependent variable is ‘Churn’ & \nindependent variables are ‘tenure’ & ‘MonthlyCharges’ \ni. Divide the dataset in 80:20 ratio \nii. Build the model on train set and predict the values on test set \niii. Build the confusion matrix and get the accuracy score'

In [ ]:
y=df['Churn']

In [ ]:
x=pd.DataFrame(df.loc[:,['MonthlyCharges','tenure']])

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(x,y, train_size=0.8, random_state=0)

In [ ]:
model= LogisticRegression()

In [ ]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5634 entries, 2920 to 2732
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MonthlyCharges  5634 non-null   float64
 1   tenure          5634 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 132.0 KB

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred= model.predict(x_test)

In [ ]:
accuracy_score(y_pred,y_test)

0.7735982966643009

In [ ]:
confusion_matrix(y_pred,y_test)

array([[934, 212],
       [107, 156]])

In [ ]:
'''Decision Tree:
a.
Build a decision tree model where dependent variable is ‘Churn’ & independent
variable is ‘tenure’
i. Divide the dataset in 80:20 ratio
ii.Build the model on train set and predict the values on test set
iii. Build the confusion matrix and calculate the accuracy '''

'Decision Tree: \na. \nBuild a decision tree model where dependent variable is ‘Churn’ & independent \nvariable is ‘tenure’ \ni. Divide the dataset in 80:20 ratio \nii.Build the model on train set and predict the values on test set  \niii. Build the confusion matrix and calculate the accuracy '

In [ ]:
r=pd.DataFrame(df['tenure'])

In [ ]:
s=df['Churn']

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(r,s,train_size=0.8,random_state=10)

In [ ]:

from sklearn.tree import DecisionTreeClassifier

In [ ]:
model= DecisionTreeClassifier(max_depth=3, random_state=0)

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [ ]:


y_pred= model.predict(x_test)

In [ ]:

accuracy_score(y_pred,y_test)

0.7771469127040455

In [ ]:
confusion_matrix(y_pred,y_test)

array([[991, 239],
       [ 75, 104]])